# section 06 working with data part2

In [13]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### Merge

In [2]:
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'], 'data_set_1':np.arange(6)})
dframe1

key  data_set_1
0   X           0
1   Z           1
2   Y           2
3   Z           3
4   X           4
5   X           5

In [3]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})
dframe2

key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [4]:
pd.merge(dframe1, dframe2)

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [5]:
pd.merge(dframe1, dframe2, on='key')

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [6]:
pd.merge(dframe1, dframe2, on='key', how='left')

key  data_set_1  data_set_2
0   X           0         NaN
1   Z           1         3.0
2   Y           2         2.0
3   Z           3         3.0
4   X           4         NaN
5   X           5         NaN

In [7]:
pd.merge(dframe1, dframe2, on='key', how='right')

key  data_set_1  data_set_2
0   Z         1.0           3
1   Z         3.0           3
2   Y         2.0           2
3   Q         NaN           1

### Merge on Index

In [3]:
df_left = DataFrame({'key' : ['X','Y','Z','X','Y'], 'data' : range(5)})
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [4]:
df_right = DataFrame({'group_date' : [10,20]}, index=['X','Y'])
df_right

group_date
X          10
Y          20

In [7]:
pd.merge(df_left, df_right, left_on='key', right_index=True)

key  data  group_date
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [8]:
pd.merge(df_left, df_right, left_on='key', right_index=True, how='outer')

key  data  group_date
0   X     0        10.0
3   X     3        10.0
1   Y     1        20.0
4   Y     4        20.0
2   Z     2         NaN

In [10]:
df_left_hr = DataFrame({'key1' : ['SF','SF','SF','LA','LA'],
                       'key2' : [10,20,30,20,30],
                       'data_set' : np.arange(5)})
df_left_hr

key1  key2  data_set
0   SF    10         0
1   SF    20         1
2   SF    30         2
3   LA    20         3
4   LA    30         4

In [11]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
                        index=[['LA','LA','SF','SF','SF'],
                                [20,10,10,10,20]],
                        columns=['col_1','col_2'])
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [12]:
pd.merge(df_left_hr, df_right_hr, left_on=['key1','key2'],right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10         0      4      5
0   SF    10         0      6      7
1   SF    20         1      8      9
3   LA    20         3      0      1

### Concatenate

In [14]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [16]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [19]:
ser1

T    0
U    1
V    2
dtype: int64

In [20]:
ser2

X    3
Y    4
dtype: int64

### Combining DataFrames

### Reshaping

### Pivoting

### Duplicates in DataFrames

### Mapping

### Replace

### Rename Index

### Binning

### Outliers

### Permutation